- name: install Flask framework 
  yum:
    name:
      - python-flask-admin 
      - python-flask-babel 
      - python-flask-cache 
      - python-flask-cache-doc 
      - python-flask-doc 
      - python-flask-mako 
      - python-flask-openid 
      - python-flask-rstpages 
      - python-flask-script 
      - python-flask-whooshalchemy 
      - python-flask-wtf 
      - python-flask-xml-rpc 
      - python2-fedora-flask 
      - python2-flask-login 
      - python2-flask-migrate 
      - python2-flask-multistatic 
      - python2-flask-oidc 
      - python2-flask-restful 
      - python2-flask-sqlalchemy 
      - python-flask 
      - python2-mimerender 
