- name: Configure Web servers 
  hosts: all 
  tasks: 
  - name: Install httpd server
    yum: 
      name: httpd 
      state: latest
  - name: Start required Services 
    service: 
      name: "{{ item }}" 
      state: running
      enabled: true
    with_items:
      - firewalld 
      - httpd
  - name: Configure firewalld 
    firewalld:
      permanent: true  
      service: http
      state: enabled 
- name: Configure web content 
  hosts: backends
  tasks: 
  - name: deploy web content per server
    copy: 
      src: "webcontent/{{ content }}/{{item}}"
      dest: /var/www/html
    with_items: 
      - index.html
      - index_fichiers
